### ISSUE TITLE
Map inset zoom

### ISSUE THREAD

**Issue by rbjansen** [prio-data/views_dataviz#18]
## For example 
![inset_test](https://user-images.githubusercontent.com/31345940/141286407-3c686a8d-1650-4a5a-aae0-2412b21f5563.png)

**Comment by hhegre** [comment]
Have you written a demonstration notebook based on data from ViEWSER for the mapping tools, as I mentioned earlier? Sorry if I missed something.

**Comment by rbjansen** [comment]
@hhegre I haven't yet been able to add that given the 5xx errors.

**Comment by hhegre** [comment]
You can take the notebook I showed you on Tuesday  and the  queryset I have there (https://github.com/prio-data/predicting_fatalities/blob/master/notebooks/HH_views3_fatalities.ipynb) - that queryset works for me.

**Comment by rbjansen** [comment]
I've encountered an additional obstacle. Described in issue #22
