### ISSUE TITLE
Mapping examples with viewser

### ISSUE THREAD

**Issue by rbjansen** [prio-data/views_dataviz#20]
It would be helpful for the mapper example notebook to fetch data (including the geometries) using a viewser queryset.

**Comment by hhegre** [comment]
What is the status for this? It would be useful to have available a preliminary version where the data to plot are from a viewser queryset even if the geometries are fetched as before. Then we can start testing and using it.

**Comment by rbjansen** [comment]
This is added to the example notebook now.
