### ISSUE TITLE
Make a Africa + Middle East preset for the mapper

### ISSUE THREAD

**Issue by hhegre** [prio-data/views_dataviz#23]
I think perhaps a preset for the current data coverage would be useful. Africa and Middle East as defined for ViEWS3; that is including Turkey and Iran.

**Comment by rbjansen** [comment]
I've replaced the mapping preset with `ViewsMap`, which you can set with `bbox="africa"`, `bbox="africa_middle_east"` or `bbox=None`. See the notebook for an example.
